export function useMDXComponents(components) {
  return {
    h1: (props) => <h1 {...props} />,
    h2: (props) => <h2 {...props} />,
    h3: (props) => <h3 {...props} />,
    h4: (props) => <h4 {...props} />,
    h5: (props) => <h5 {...props} />,
    h6: (props) => <h6 {...props} />,
    p: (props) => <p {...props} />,
    a: (props) => <a {...props} />,
    ul: (props) => <ul {...props} />,
    ol: (props) => <ol {...props} />,
    li: (props) => <li {...props} />,
    code: (props) => <code {...props} />,
    pre: (props) => <pre {...props} />,
    table: (props) => <table {...props} />,
    thead: (props) => <thead {...props} />,
    tbody: (props) => <tbody {...props} />,
    tr: (props) => <tr {...props} />,
    th: (props) => <th {...props} />,
    td: (props) => <td {...props} />,
    blockquote: (props) => <blockquote {...props} />,
    hr: (props) => <hr {...props} />,
    strong: (props) => <strong {...props} />,
    em: (props) => <em {...props} />,
    ...components,
  }
}
